/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "send_time.h"


void
send_time_1(char *host) {
    CLIENT *clnt;
    datetime *result_1;
    char *send_1_arg;

#ifndef    DEBUG
    clnt = clnt_create(host, SEND_TIME, SEND_TIME_1, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif	/* DEBUG */

    result_1 = send_1((void *) &send_1_arg, clnt);
    if (result_1 == (datetime *) NULL) {
        clnt_perror(clnt, "call failed");
    }
    printf("year : %d , month : %d , day : %d , hour : %d , minute : %d , sec : %d", result_1->year,
           result_1->month, result_1->day, result_1->hour, result_1->minute, result_1->sec);

#ifndef    DEBUG
    clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main(int argc, char *argv[]) {
    char *host;

    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    send_time_1(host);
    exit(0);
}
